add_newline = true

format = """\
  $kubernetes\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $python\
  $ruby \
  $line_break\
  $character\
  """
  
[aws]
disabled = true

[kubernetes]
disabled = false

[character]
success_symbol = "[ζ](bold green)"
error_symbol = "[ζ](bold red)"

[directory]
truncation_length = 7
truncate_to_repo = true