add_newline = true

prompt_order = [
  "kubernetes",
  "directory",
  "git_branch",
  "git_commit",
  "git_state",
  "git_status",
  "python",
  "line_break",
  "character"
]

[aws]
disabled = true

[kubernetes]
disabled = false

[character]
symbol = "Î¶"