#! /bin/sh

sxhkd &
polybar example &
wmname LG3D &
xscreensaver -nosplash &
gnome-keyring-daemon -c secrets &
tilda &
dunst &
setxkbmap -option 'ctrl:nocaps,compose:menu'
copyq &
davmail &


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
