add_newline = true
format = "$hostname$directory$gcloud$git_branch$git_commit$git_state$line_break$character"

[character]
error_symbol = "[ζ](bold red)"
success_symbol = "[ζ](bold green)"

[directory]
truncate_to_repo = "true"
truncation_length = 3

[hostname]
ssh_only = "true"
trim_at = "."
